### ISSUE TITLE
XMs output by new versions of OpenMPT do not get samples.h generated by krawerter correctly - only the original mpt.exe from 2004 writes XMs that work.

### ISSUE THREAD

**Issue by chr15m** [sebknzl/krawall#4]
Not really an important bug, but just a heads-up! :)

**Comment by StarWolf3000** [comment]
Probably too late now, but in OpenMPT save your file with "Compatibility Export". OpenMPT supports some non-standard extensions to the original formats.

**Comment by chr15m** [comment]
Cool, thanks!
